import { useMemo, useState } from 'react'
import { Info, Receipt } from 'lucide-react'
import { Card } from '../../../shared/components/dashboard/DashboardKit'
import { SearchableSelect } from '../../../shared/components/forms/SearchableSelect'
import { ListPagination } from '../../../shared/components/ListPagination'
import { useUsersSummary } from '../../users/users.queries'

const inputCls = 'h-9 px-3 rounded-md border border-input-border bg-input-bg text-text text-sm outline-none focus:ring-2 focus:ring-brand/30'
const PAGE_SIZE_OPTIONS = [15, 25, 50, 100]

// payroll/gratuity_payment.php's employee/status table comes from
// payroll/ajax_search.php?EmpGratuityPay=1 as an HTML fragment — not
// scraped here. Its real saveGratuityPayment write also needs a pre-existing
// payment_id/expenceid per row that only exists inside that same fragment's
// output (a gratuity record generated by some earlier real payroll-
// processing step this module doesn't have visibility into) — so, same
// honesty as Make Payment, this reproduces the real search flow and table
// shape but doesn't fabricate rows or wire Pay All to a write it can't
// responsibly perform.
export function GratuityPaymentForm() {
  const { data: users } = useUsersSummary()

  const [year, setYear] = useState('')
  const [employeeId, setEmployeeId] = useState('')
  const [paymentMethod, setPaymentMethod] = useState<'Cash' | 'Online'>('Cash')
  const [hasSearched, setHasSearched] = useState(false)
  const [error, setError] = useState('')
  const [page, setPage] = useState(1)
  const [perPage, setPerPage] = useState(15)

  const employeeOptions = useMemo(() => (users?.users ?? []).map((u) => ({ value: String(u.id), label: u.name || u.login })), [users])
  const yearOptions = useMemo(() => {
    const base = new Date().getFullYear()
    return Array.from({ length: 12 }, (_, i) => String(base - 5 + i))
  }, [])

  function handleGo() {
    setError('')
    if (!year) return setError('Select a year.')
    if (!employeeId) return setError('Select an employee.')
    setHasSearched(true)
    setPage(1)
  }
  function handlePerPageChange(value: number) {
    setPerPage(value)
    setPage(1)
  }

  return (
    // -m-6/-mx-6/-top-6: same sticky-header pattern as ManualShiftAttendanceForm.tsx /
    // StickyFormShell.tsx — sticky's offset is measured from the scrolling ancestor's
    // padding edge, so the negative offsets compensate for AppShell main's own p-6 inset.
    <div className="-m-6 flex-1 flex flex-col min-h-0">
      <div className="sticky -top-6 z-10 -mx-6 border-b border-border bg-white px-6 py-3 dark:bg-gray-950 space-y-3">
        <h2 className="flex items-center gap-2 text-lg font-bold text-text!">
          <Receipt size={20} className="text-brand" /> Gratuity Payment
        </h2>

        <Card className="!h-auto flex items-start gap-2 bg-info-bg/40">
          <Info size={15} className="text-info-fg mt-0.5 shrink-0" />
          <p className="text-xs text-info-fg">
            Backend page: <code className="font-mono">payroll/gratuity_payment.php</code>. Its real employee/gratuity table comes from an HTML-fragment
            endpoint, and its Pay All write needs pre-existing payment record ids that only exist inside that same fragment — neither is reproduced here, so
            the table below stays empty and Pay All is disabled.
          </p>
        </Card>

        <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 items-end">
          <div>
            <label className="block text-xs text-danger mb-1">Select Year *</label>
            <select value={year} onChange={(e) => setYear(e.target.value)} className={`w-full ${inputCls}`}>
              <option value="">Select Year</option>
              {yearOptions.map((y) => (
                <option key={y} value={y}>
                  {y}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-xs text-danger mb-1">Select Employee *</label>
            <SearchableSelect value={employeeId} onChange={setEmployeeId} options={employeeOptions} placeholder="Select Employee..." />
          </div>
          <button type="button" onClick={handleGo} className="h-9 rounded-md bg-brand px-4 text-sm font-medium text-white hover:bg-brand-hover">
            GO
          </button>
          {hasSearched && (
            <div>
              <label className="block text-xs text-danger mb-1">Payment Method *</label>
              <select value={paymentMethod} onChange={(e) => setPaymentMethod(e.target.value as 'Cash' | 'Online')} className={`w-full ${inputCls}`}>
                <option value="Cash">Cash</option>
                <option value="Online">Online</option>
              </select>
            </div>
          )}
        </div>
        {error && <p className="text-xs text-danger">{error}</p>}
      </div>

      {hasSearched && (
        <div className="flex-1 flex flex-col min-h-0 -mx-6 px-6 py-4">
          <Card className="!p-0 overflow-hidden flex-1 min-h-0">
            <div className="flex flex-wrap items-center gap-3 p-3 border-b border-border">
              <div className="flex items-center gap-2 ml-auto">
                <select
                  value={perPage}
                  onChange={(e) => handlePerPageChange(Number(e.target.value))}
                  className="text-sm rounded-md border border-input-border bg-input-bg text-text px-2 py-1.5"
                >
                  {PAGE_SIZE_OPTIONS.map((n) => (
                    <option key={n} value={n}>
                      {n}
                    </option>
                  ))}
                </select>
                <button
                  type="button"
                  disabled
                  title="No confirmed write endpoint for this action — see the banner above"
                  className="h-9 rounded-md border border-input-border px-4 text-sm font-medium text-text-muted opacity-50 cursor-not-allowed"
                >
                  Pay All
                </button>
              </div>
            </div>
            <div className="flex-1 min-h-0 overflow-auto">
              <table className="w-full text-sm">
                <thead className="sticky top-0 z-10">
                  <tr className="text-left text-xs text-text-faint uppercase tracking-wide border-b border-border bg-surface">
                    <th className="font-medium px-3 py-2 w-10">
                      <input type="checkbox" disabled title="Pay All isn't wired — see the banner above" />
                    </th>
                    <th className="font-medium px-3 py-2">Month</th>
                    <th className="font-medium px-3 py-2">Currency</th>
                    <th className="font-medium px-3 py-2">Basic Salary</th>
                    <th className="font-medium px-3 py-2">Gratuity Amount</th>
                    <th className="font-medium px-3 py-2">Payment Mode</th>
                    <th className="font-medium px-3 py-2">Status</th>
                    <th className="font-medium px-3 py-2">Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td colSpan={8} className="px-3 py-4 text-text-faint italic">
                      No Data Available In Table
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </Card>
        </div>
      )}

      {hasSearched && <ListPagination page={page} perPage={perPage} total={0} onPageChange={setPage} edgeToEdge />}
    </div>
  )
}
