import { useMemo, useState } from 'react'
import { Info, Receipt } from 'lucide-react'
import { Card } from '../../../shared/components/dashboard/DashboardKit'
import { SearchableSelect } from '../../../shared/components/forms/SearchableSelect'
import { useUsersSummary } from '../../users/users.queries'

const inputCls = 'h-9 px-3 rounded-md border border-input-border bg-input-bg text-text text-sm outline-none focus:ring-2 focus:ring-brand/30'

// payroll/gratuity_payment.php's employee/status table comes from
// payroll/ajax_search.php?EmpGratuityPay=1 as an HTML fragment — not
// scraped here. Its real saveGratuityPayment write also needs a pre-existing
// payment_id/expenceid per row that only exists inside that same fragment's
// output (a gratuity record generated by some earlier real payroll-
// processing step this module doesn't have visibility into) — so, same
// honesty as Make Payment, this reproduces the real search flow and table
// shape but doesn't fabricate rows or wire Pay All to a write it can't
// responsibly perform.
export function GratuityPaymentForm() {
  const { data: users } = useUsersSummary()

  const [year, setYear] = useState('')
  const [employeeId, setEmployeeId] = useState('')
  const [paymentMethod, setPaymentMethod] = useState<'Cash' | 'Online'>('Cash')
  const [hasSearched, setHasSearched] = useState(false)
  const [error, setError] = useState('')

  const employeeOptions = useMemo(() => (users?.users ?? []).map((u) => ({ value: String(u.id), label: u.name || u.login })), [users])
  const yearOptions = useMemo(() => {
    const base = new Date().getFullYear()
    return Array.from({ length: 12 }, (_, i) => String(base - 5 + i))
  }, [])

  function handleGo() {
    setError('')
    if (!year) return setError('Select a year.')
    if (!employeeId) return setError('Select an employee.')
    setHasSearched(true)
  }

  return (
    <div className="space-y-4">
      <h2 className="flex items-center gap-2 text-lg font-bold text-text!">
        <Receipt size={20} className="text-brand" /> Gratuity Payment
      </h2>

      <Card className="!h-auto flex items-start gap-2 bg-info-bg/40">
        <Info size={15} className="text-info-fg mt-0.5 shrink-0" />
        <p className="text-xs text-info-fg">
          Backend page: <code className="font-mono">payroll/gratuity_payment.php</code>. Its real employee/gratuity table comes from an HTML-fragment
          endpoint, and its Pay All write needs pre-existing payment record ids that only exist inside that same fragment — neither is reproduced here, so
          the table below stays empty and Pay All is disabled.
        </p>
      </Card>

      <Card className="!h-auto">
        <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 items-end">
          <div>
            <label className="block text-xs text-danger mb-1">Select Year *</label>
            <select value={year} onChange={(e) => setYear(e.target.value)} className={`w-full ${inputCls}`}>
              <option value="">Select Year</option>
              {yearOptions.map((y) => (
                <option key={y} value={y}>
                  {y}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-xs text-danger mb-1">Select Employee *</label>
            <SearchableSelect value={employeeId} onChange={setEmployeeId} options={employeeOptions} placeholder="Select Employee..." />
          </div>
          <button type="button" onClick={handleGo} className="h-9 rounded-md bg-brand px-4 text-sm font-medium text-white hover:bg-brand-hover">
            GO
          </button>
          {hasSearched && (
            <div>
              <label className="block text-xs text-danger mb-1">Payment Method *</label>
              <select value={paymentMethod} onChange={(e) => setPaymentMethod(e.target.value as 'Cash' | 'Online')} className={`w-full ${inputCls}`}>
                <option value="Cash">Cash</option>
                <option value="Online">Online</option>
              </select>
            </div>
          )}
        </div>
        {error && <p className="text-xs text-danger mt-2">{error}</p>}
      </Card>

      {hasSearched && (
        <>
          <div className="flex justify-end">
            <button
              type="button"
              disabled
              title="No confirmed write endpoint for this action — see the banner above"
              className="h-9 rounded-md border border-input-border px-4 text-sm font-medium text-text-muted opacity-50 cursor-not-allowed"
            >
              Pay All
            </button>
          </div>
          <Card className="!p-0 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-left text-xs text-text-faint uppercase tracking-wide border-b border-border bg-surface">
                    <th className="font-medium px-3 py-2 w-10">
                      <input type="checkbox" disabled title="Pay All isn't wired — see the banner above" />
                    </th>
                    <th className="font-medium px-3 py-2">Month</th>
                    <th className="font-medium px-3 py-2">Currency</th>
                    <th className="font-medium px-3 py-2">Basic Salary</th>
                    <th className="font-medium px-3 py-2">Gratuity Amount</th>
                    <th className="font-medium px-3 py-2">Payment Mode</th>
                    <th className="font-medium px-3 py-2">Status</th>
                    <th className="font-medium px-3 py-2">Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td colSpan={8} className="px-3 py-4 text-text-faint italic">
                      No Data Available In Table
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </Card>
        </>
      )}
    </div>
  )
}
